version: "3.9"
name: pysect-backend-challenge-prod
services:

  db-prod:
    image: "postgres:13.10-alpine"
    container_name: pysect-backend-db-prod
    restart: unless-stopped
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.prod

  redis-prod:
    image: redis:latest
    container_name: pysect-backend-redis-prod
    networks:
      - nginx-reverse-proxy-net

  web-prod:
    image: "pysect-backend-challenge-prod"
    container_name: pysect-backend-challenge-prod
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - django-static-prod:/var/www/django/static
      - /home/pi/pysect-logs-prod:/var/www/log
      # We should only mount source code in development:
      - .:/code
    depends_on:
      - db-prod
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.prod
    environment:
      VIRTUAL_HOST: py.sect.letz.dev
      VIRTUAL_PATH: ~^/(api|static)/
      VIRTUAL_PORT: 8000
    command: ./docker/django/local_run.sh

networks:
  nginx-reverse-proxy-net:
    external: true

volumes:
  pgdata-prod:
  django-static-prod:
