---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.9"
services:

  db-dev:
    image: "postgres:13.10-alpine"
    container_name: pysect-dev-backend-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env

  redis-dev:
    image: redis:latest
    container_name: pysect-dev-backend-redis
    networks:
      - nginx-reverse-proxy-net

  web-dev:
    image: "pysect-dev-backend"
    container_name: pysect-dev-backend-core
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: production
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - django-static:/var/www/django/static
      - /home/pi/pysect-logs:/var/www/log
      # We should only mount source code in development:
      - .:/code
    depends_on:
      - db-dev
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env
    environment:
      VIRTUAL_HOST: py.sect.test.letz.dev
      VIRTUAL_PATH: ~^/(api|static)/
      VIRTUAL_PORT: 8000
    command: ./docker/django/local_run.sh

networks:
  # Network for your internals, use it by default:
  nginx-reverse-proxy-net:
    external: true

volumes:
  pgdata:
  django-static:
