version: "3.9"
name: pysect-backend-challenge-dev
services:

  db-dev:
    image: "postgres:13.10-alpine"
    container_name: pysect-backend-db-dev
    restart: unless-stopped
    ports:
      - "5555:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.dev

  redis-dev:
    image: redis:latest
    container_name: pysect-backend-redis-dev
    networks:
      - nginx-reverse-proxy-net

  web-dev:
    image: "pysect-backend-challenge-dev"
    container_name: pysect-backend-challenge-dev
    #platform: linux/amd64
    build:
      target: builder_image
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        # See: https://github.com/wemake-services/wemake-django-template/issues/1518
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - django-static-dev:/var/www/django/static
      - /home/pi/pysect-logs-dev:/var/www/log
      # We should only mount source code in development:
      - .:/code
    depends_on:
      - db-dev
    networks:
      - nginx-reverse-proxy-net
    env_file:
      - ./docker/config/.env.dev
    environment:
      VIRTUAL_HOST: py.sect.test.letz.dev
      VIRTUAL_PATH: ~^/(api|static)/
      VIRTUAL_PORT: 8000
    command: ./docker/django/local_run.sh

networks:
  nginx-reverse-proxy-net:
    external: true

volumes:
  pgdata-dev:
  django-static-dev:
