# Generated by Django 4.2.7 on 2023-11-25 23:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward', models.IntegerField()),
                ('input_sample', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('output_sample', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('memory_limit', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('input_path', models.CharField(max_length=255)),
                ('output_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'python challenge',
                'verbose_name_plural': 'python challenges',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('output', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=list, size=None)),
                ('error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_ready', 'not_ready'), ('ready', 'ready'), ('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='not_ready', max_length=100)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to='core.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.user')),
            ],
            options={
                'verbose_name': 'python challenge submission',
                'verbose_name_plural': 'python challenge submissions',
                'db_table': 'challenge_submissions',
            },
        ),
    ]
