# Generated by Django 4.2.7 on 2023-11-12 22:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reward', models.IntegerField()),
            ],
            options={
                'verbose_name': 'python challenge',
                'verbose_name_plural': 'python challenges',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('error', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to='core.challenge')),
            ],
            options={
                'verbose_name': 'python challenge result',
                'verbose_name_plural': 'python challenge results',
                'db_table': 'challenge_results',
            },
        ),
        migrations.CreateModel(
            name='ChallengeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_inputs', to='core.challenge')),
            ],
            options={
                'verbose_name': 'python challenge input',
                'verbose_name_plural': 'python challenge inputs',
                'db_table': 'challenge_inputs',
            },
        ),
    ]
