# Generated by Django 4.2.7 on 2023-11-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='challengesubmission',
            name='unique_challenge_user_success',
        ),
    ]
