# Generated by Django 5.0 on 2023-12-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='lambda_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
