# Generated by Django 5.0 on 2024-01-27 03:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.DecimalField(choices=[(Decimal('0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0')], decimal_places=1, max_digits=2),
        ),
    ]
