# Generated by Django 4.2.7 on 2023-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_challengesubmission_unique_challenge_user_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='error',
            field=models.TextField(),
        ),
    ]
