# Generated by Django 5.0 on 2024-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_challenge_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='input_sample',
            field=models.JSONField(),
        ),
    ]
