# Generated by Django 4.2.7 on 2023-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_challengesubmission_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='memory',
            new_name='memory_limit',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='time',
            new_name='time_limit',
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
