# Generated by Django 5.0 on 2023-12-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_challengesubmission_error_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengesubmission',
            name='src_path',
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='src_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
