# Generated by Django 5.0 on 2024-07-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_challenge_input_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='output_sample',
            field=models.JSONField(),
        ),
    ]
