# Generated by Django 5.0 on 2023-12-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_challengesubmission_src_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='input_path',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='output_path',
        ),
        migrations.AddField(
            model_name='challenge',
            name='input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
