# Generated by Django 5.0 on 2023-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_challenge_input_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('ready', 'Ready'), ('broken', 'Broken'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='not_ready', max_length=100),
        ),
    ]
