# Generated by Django 5.0 on 2024-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_challenge_output_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='input',
            field=models.JSONField(),
        ),
    ]
