# Generated by Django 5.0 on 2024-01-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_challengesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('broken', 'Broken'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='ready', max_length=100),
        ),
    ]
