# Generated by Django 5.0 on 2024-01-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_challengesubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengesubmission',
            name='lambda_name',
        ),
    ]
