# Generated by Django 5.0 on 2024-01-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_challengesubmission_lambda_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='subtitle',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
