# Generated by Django 5.0 on 2024-01-20 23:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_challenge_subtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeSubmission',
            new_name='Submission',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='submissions',
        ),
    ]
