# Generated by Django 5.0 on 2024-01-26 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='available_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reward',
            name='redemption',
            field=models.ManyToManyField(blank=True, related_name='redeemed_rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
